import pandas as pd 
import numpy 
import functions
import seaborn as sns
first_data = pd.read_csv('/home/oh856/Downloads/Performance/real_performance.csv')
second_data = pd.read_csv('/home/oh856/Downloads/Performance/hourlyperf/slower/Order Execution.csv')

clean_first_data = functions.outlier_processing(first_data)
clean_second_data = functions.outlier_processing(second_data)

print('#### First Data Describe:')
print('        ')
print('        ')
print(pd.DataFrame(clean_first_data['order_exe_time_millis']).describe().T)
print('        ')
print('        ')
print('        ')
print('        ')
print('        ')
print('        ')
print('        ')
print('#### Second Data Describe:     ')
print('        ')
print('        ')
print(pd.DataFrame(clean_second_data['order_exe_time_millis']).describe().T)
print('        ')
print('        ')
print('        ')
print('        ')
print('        ')
print('        ')
print('        ')
print('Confidence Interval for first dataset:')
print('        ')
print('        ')
print((functions.confidence_interval(clean_first_data['order_exe_time_millis']))) 
print('        ')
print('        ')
print('        ')
print('        ')
print('        ')
print('        ')
print('Confidence Interval for second dataset:')
print('        ')
print('        ')
print((functions.confidence_interval(clean_second_data['order_exe_time_millis']))) 
print('        ')
print('        ')
print('        ')
print('        ')
print('        ')
print('        ')


print('#################  OUTLIERS INFORMATION  #################')

#first_data = pd.read_csv('/home/oh856/Downloads/Performance/real_performance.csv')
#second_data = pd.read_excel('/home/oh856/Downloads/Performance/artifical.xlsx')

outliers_first_data = functions.outlier_control(first_data,'order_exe_time_millis')
outliers_second_data = functions.outlier_control(second_data,'order_exe_time_millis')
print('        ')
print('        ')


print('#### First Data Describe:')
print('        ')
print('        ')
print(pd.DataFrame(outliers_first_data['order_exe_time_millis']).describe().T)
print('        ')
print('        ')
print('        ')
print('        ')
print('        ')
print('        ')
print('        ')
print('#### Second Data Describe:     ')
print('        ')
print('        ')
print(pd.DataFrame(outliers_second_data['order_exe_time_millis']).describe().T)
print('        ')
print('        ')
print('        ')
print('        ')
print('        ')
print('        ')
print('        ')
print('Confidence Interval for first dataset:')
print('        ')
print('        ')
print((functions.confidence_interval(outliers_first_data['order_exe_time_millis']))) 
print('        ')
print('        ')
print('        ')
print('        ')
print('        ')
print('        ')
print('Confidence Interval for second dataset:')
print('        ')
print('        ')
print((functions.confidence_interval(outliers_second_data['order_exe_time_millis']))) 