---

- name: use student.bash_env role playbook
  hosts: localhost
  vars:
    default_prompt: '[\u on \h in \W dir]\$ '
    prompt_color: blue
  pre_tasks:
   - name: Ensure test user does not exist
     user:
       name: student2
       state: absent
       force: yes
       remove: yes

  roles:
   - student.bash_env

  post_tasks:
   - name: Create the test user
     user:
       name: student2
       state: present
       password: "{{ 'redhat' | password_hash('sha512', 'mysecretsalt') }}"

