---
- name: Create multiple local users
  hosts: localhost
  vars_files:
    - group_vars/users/users_vars.yml
  tasks:
    - name: Add webadmin group
      group:
        name: webadmin
        state: present

    - name: Create user accounts
      user:
        name: "{{ item.username }}"
        groups: webadmin
      loop: "{{ users }}"
