# Generated by Django 4.0 on 2024-03-23 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter first name of the contributor', max_length=250)),
                ('surname', models.CharField(help_text='Enter surname of the contributor', max_length=500)),
                ('about', models.CharField(help_text='Tell us about yourself, your experience and current work', max_length=2000)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'ordering': ['surname', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title for a new article', max_length=250)),
                ('text', models.CharField(help_text='Place your story here', max_length=1000)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogsite.contributor')),
            ],
        ),
    ]
